### ISSUE TITLE
Example with Laravel Livewire

### ISSUE THREAD

**Issue by anardil** [mgussekloo/laravel-facet-filter#1]
Hello,

Firstable, thanks for your amazing package.
Do you have a full example with Laravel Livewire?
I never used Laravel LiveWire and it seems very cool with your package.

Thank you.

**Comment by mgussekloo** [comment]
Thanks! I've been meaning to publish a full example project, but haven't had the time to do so yet. Livewire is handy because it handles the interactive part (updating the filter array on the backend, based on checked input boxes on the frontend). Simply make a component, and in the render() function get the models (e.g. Product::facetsMatchFilter($this->filter);) and facets (e.g. Product::getFacets($this->filter);) so you can render them in the template. Hope this helps!

**Comment by anardil** [comment]
Thanks for your reply. I will try.
Another thing, is it possible to have a price range with your system?

Thank you.

**Comment by mgussekloo** [comment]
Having a range facet type would be a great addition to be honest. Right now, the only option would be extending the [Mgussekloo\FacetFilter\Indexer](https://github.com/mgussekloo/laravel-facet-filter/blob/master/src/Indexer.php) class (or doing your own indexing). Add the "range bracket" value to the index, instead of the "individual price" value.

Overwrite the "buildRow" function like (example);

public function buildRow($facet, $model, $value) {
$row = parent::buildRow($facet, $model, $value);
if ($facet->getSlug() == 'pricerange') {
if ($row['value'] > 0 && $row['value'] < 100) {
$row['value'] = '0-100';
}
return $row;
}

Please let me know if you end up making a range facet, maybe it can be added to this repo!

**Comment by anardil** [comment]
Hi,

Thanks for the buildRow method.
I tried and it works fine :)
I just replace if ($facet->getSlug() == 'pricerange') { 
by
if ($facet->getSlug() == 'App\Models\Product.price') {

Another thing, how can I reorder the facets options? Because range values are not in the good order.
Thanks.

**Comment by anardil** [comment]
I have a problem with filtering. It doesn't work.

$filter = Product::getFilterFromArr(['color' => 'black']);
$products = Product::facetsMatchFilter($filter)->get();

I don't get products with color black but all products.
'color' is it the property column name in my table or is the slug name in your table?

Thanks.

**Comment by mgussekloo** [comment]
Great! The options are a regular Laravel collection, so you can sort them with something like [sortBy](https://laravel.com/docs/10.x/collections#method-sortby).
